### PR TITLE
Skip modules with an empty path.

### PR DESCRIPTION
**Pull request by ademuri**
I was getting errors on the path -> uid parsing logic. I'm not sure why
one of the modules had an empty path, but with this change I still get
the correct number of components in the position file.

Also fix a few errants tabs that should be spaces.

### CODE REVIEW

**Comment by essele** [comment]
> I was getting errors on the path -> uid parsing logic. I'm not sure why
> one of the modules had an empty path, but with this change I still get
> the correct number of components in the position file.
> 
> Also fix a few errants tabs that should be spaces.

Hi Ademuri,

Thankyou for the contribution!

I actually had a similar fix in my working tree as I found a problem on one of my new designs. Could you try this and see if it works for you...

```
diff --git a/jlcpcba_main.py b/jlcpcba_main.py
index 337ff32..df170e6 100644
--- a/jlcpcba_main.py
+++ b/jlcpcba_main.py
@@ -204,7 +204,11 @@ def create_pcba():
     for m in board.GetModules():
         #uid = m.GetPath().replace('/', '')
        # Need to just pull out the non-zero part at the end
-       uid = m.GetPath().AsString().lower()
+       if hasattr(m.GetPath(), 'AsString'):
+               uid = m.GetPath().AsString().lower()
+       else:
+               uid = m.GetPath().lower()
+
        while (uid[0] in "0/-"):
                uid = uid[1:]

```
(I'll commit it to the main tree in the meantime, and then revisit if it doesn't fix the problem you found.)

Thanks,

Lee.

**Comment by ademuri** [comment]
That fixes one of the problems that I'm seeing (AsString not existing). I'm still seeing two other problems:

1. Mixed usage of spaces and tabs:
`TabError('inconsistent use of tabs and spaces in indentation', ('/home/adam/.config/kicad/scripting/kicad_jlcpcba/jlcpcba_main.py', 207, 38, "\tif hasattr(m.GetPath(), 'AsString'):\n"))`

2. Empty path in board.GetModules() - this causes:
`IndexError('string index out of range')`

2 appears to be caused by a silkscreen-only component (OSHW logo).

**Comment by essele** [comment]
Thanks … I’ve fixed the tabs, but I can’t recreate the other problem. I’ve added various logos to the board on the silkscreen layer and don’t get any errors.

Could you send me the pcb file you’re having problems with? (lee.essen@nowonline.co.uk <mailto:lee.essen@nowonline.co.uk>)

Thanks,

Lee.

**Comment by ademuri** [comment]
Sure, the KiCAD project is here: https://github.com/ademuri/wifi-volume-control/tree/master/hardware/balanced-xlr

The problematic footprint should be embedded.

**Comment by essele** [comment]
Hi Ademuri,

I believe this is fixed ... would be grateful if you could double check for me.

Lee.

**Pull request closed without merging**
